//
//  MovieNames.swift
//  Pass the Popcorn
//
//  Created by Amar Saraon on 9/4/20.
//  Copyright © 2020 Amar Saraon. All rights reserved.
//

import Foundation

enum MovieNames: String, CaseIterable {
    case backToTheFuture = "Back to the Future"
    case dieHard = "Die Hard"
    case bladeRunner = "Blade Runner"
    case toyStory = "Toy Story"
    case blackPanther = "Black Panther"
    case theDarkKnight = "The Dark Knight"
    case jaws = "Jaws"
    case getOut = "Get Out"
    case lifeOfBrian = "Monty Python's Life of Brian"
    case theSocialNetwork = "The Social Network"
    case jurassicWorld = "Jurassic World"
    case avatar = "Avatar"
    case frozen = "Frozen"
    case spiderman = "Spider-Man"
    case jumanji = "Jumanji: Welcome to the Jungle"
    case oceansEleven = "Ocean's Eleven"
    case ironMan = "Iron Man"
    case riseOfThePlanetOfTheApes = "Rise of the Planet of the Apes"
    case piratesOfTheCaribbean = "Pirates of the Caribbean: The Curse of the Black Pearl"
    case deadpool = "Deadpool"
    case kingKong = "King Kong"
    case wreckItRalph = "Wreck-It Ralph"
    case harryPotterSS = "Harry Potter and the Sorcerer's Stone"
    case ratatouille = "Ratatouille"
    case threeHundred = "300"
    case theHungerGames = "The Hunger Games"
    case suicideSquad = "Suicide Squad"
    case nightAtTheMusuem = "Night at the Museum"
    case johnWick = "John Wick"
    case it = "It"
    case theLegoMovie = "The Lego Movie"
    case theFastAndTheFurious = "The Fast and the Furious"
    case transformers = "Transformers"
    case guardiansOfTheGalaxy = "Guardians of the Galaxy"
    case coco = "Coco"
    case theMatrix = "The Matrix"
    case rocky = "Rocky"
    case homeAlone = "Home Alone"
    case alien = "Alien"
    case raidersOfTheLostArk = "Raiders of the Lost Ark"
    case theKarateKid = "The Karate Kid"
    case independenceDay = "Independence Day"
    case speed = "Speed"
    case superman = "Superman"
    case theShining = "The Shining"
    case ET = "E.T. the Extra-Terrestrial"
    case titanic = "Titanic"
    case ghostbusters = "Ghostbusters"
    case topGun = "Top Gun"
    case menInBlack = "Men in Black"
    case predator = "Predator"
    case missionImpossible = "Misson: Impossible"
    case theTerminator = "The Terminator"
    case casinoRoyale = "Casino Royale"
    case joker = "Joker"
    case drNo = "Dr. No"
    case theAvengers = "The Avengers"
    case starTrekTMP = "Star Trek: The Motion Picture"
    case firstBlood = "First Blood"
    case theMummy = "The Mummy"
    case halloween = "Halloween"
    case nightmareOnElmSteet = "Nightmare on Elm Street"
}
